---
title: "Lab part 1: Political activism in Greece"
author: "DL Oberski & L Boeschoten"
format: 
  html:
    theme: zephyr
    toc: true
    code-tools: true
    code-link: true
editor: visual
execute:
  cache: true
---

For this lab, we work with the Heinen (1996) dataset. This dataset consists of five dichotomous indicators on gender roles. The sample we use only contains males. The indicators correspond to the following questions:

-   AGA_MEN: A man should be the primary provider for his family (1=agree, 0=disagree)

-   NO_JOB: A woman's primary responsibility should be taking care of the home and children (1=agree, 0=disagree)

-   MAN_BRE: Men should have the final say in important family decisions (1=agree, 0=disagree)

-   NO_EDUC: It is better if women stay at home rather than pursuing education or work (1=agree, 0=disagree)

-   RAISECHI: Men and women should share responsibilities equally in a relationship (1=agree, 0=disagree)

**Question 1**

Open the dataset with Latent GOLD and run a 1, 2, 3 and 4 class model through the GUI. 

**Question 2** 

Interpret the fit of these models. Which model do you conclude fits best? 

**Question 3** 

What is the entropy $R^2$ value of your selected model? Can you interpret this value? 

**Question 4**

Provide a substantive interpretation of the latent classes. 

**Question 5** 

What is the probability of $(Y_{AGA\_MEN}=1)|X=1)$? Can you provide a substantive interpetation for this value? 

**Question 6**
Generate the syntax of your model by clicking on the button `create syntax`. Which part of the syntax allows you to specify the latent class model? 

**Question 7**
How do you specify the number of latent classes? 

**Question 8**
In the syntax, can you find the specifications of the EM algorithm? Based on the syntax, can you explain how EM is implemented in Latent GOLD? 


